highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyllt.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyllt.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Matthew's Resume
name: Matthew
email: minn2422@postech.ac.kr
email_full: mailto:minn2422@postech.ac.kr
website: github.io/sustain
website_full: https://jekyllt.github.io/sustain
github: https://github.com/matthew2123123/start
tel: +82 1040572420
tel_full: tel:+82 1040572420
google_maps: https://www.google.co.kr/maps/?hl=ko&entry=ttu
address:
  street: 77 Cheongam Street
  postcode: 37673
  city: Pohang
  country: South Korea
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
